---
Name: myproject
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: app

Playground:
    extensions:
        - AddressExtension
        
SilverStripe\Assets\Image:
    extensions:
        - GalleryImageExtension